<?php

declare(strict_types=1);

use App\Core\Template;
use App\Core\View;
use App\DTO\Response\OTPGenerateDTO;
use App\Entity\User\User;

assert(isset($user) && $user instanceof User);
assert(isset($otp) && $otp instanceof OTPGenerateDTO);

$template = new Template(
    'webstore/_base.php',
    ['title' => 'Setup 2FA']
);

?>

<?php $template->start(); ?>

<link rel="stylesheet" href="/static/styles/Account/updatePassword.css"/>
<link rel="stylesheet" href="/static/styles/Account/profile.css">

<div class="profile-container">
    <?= View::render('webstore/account/_sidebar.php', ['user' => $user, 'currentMenu' => 3]); ?>

    <div>
        <div>
            Current 2FA status: <span><?= $user->totpSecret !== null ? 'Enrolled' : 'Unenrolled' ?></span>
        </div>

        <div>
            <h2>Add a 2FA authenticator</h2>
        </div>

        <div>
            <h2>Authenticator App</h2>

            <p>
                Rather than having a One Time Password (OTP) texted to you every time you Sign-In, you will use
                an Authenticator app on your phone to generate an OTP. You will enter the generated OTP at Sign-In
                the same way as with texted OTP.
            </p>

            <ol>
                <li><b>Open</b> your Authenticator App.</li>
                <li>
                    <p><b>Add</b> an account within the app and scan the barcode below</p>
                    <img src="<?= $otp->qrUrl ?>" alt="TOTP Qr Code">
                    <button popovertarget="manual-otp">Can't scan the barcode?</button>

                    <div id="manual-otp" popover>
                        <h3>Cant scan the barcode?</h3>

                        <ol>
                            <li>Open your Authenticator App and select "Manually add account" from the menu.</li>
                            <li>In "Enter account name" type your full email address.</li>
                            <li>
                                <p>In "Enter your key" type the following key (space not required):</p>
                                <b><?= $otp->secret ?></b>
                            </li>
                            <li>Set key type to "Time based".</li>
                            <li>Tap Add.</li>
                        </ol>
                    </div>
                </li>

                <li><b>Enter OTP.</b> After you've scanned the barcode, enter the OTP generated by the app: </li>
            </ol>

            <form id="register-2fa">
                <input type="hidden" name="secret" value="<?= $otp->secret ?>">

                <label for="code"></label>
                <input type="text" name="code" id="code" required>
                <span class="validity">The code is incorrect.</span>

                <button type="submit">Verify OTP and continue</button>
            </form>
        </div>
    </div>
</div>

<script>
    $("form#register-2fa").submit(/** @param {jQuery.Event} e */ function (e) {
        e.preventDefault();

        $.ajax(
            "/api/register-2fa",
            {
                method: "POST",
                data: $(e.target).serialize(),
                success: () => {
                    window.location.reload();
                },
                error: (xhr) => {
                    switch (xhr.status) {
                        case 401:
                            $('input#code')[0].setCustomValidity("The code is incorrect.");
                    }
                }
            }
        )
    });

    $("input#code").change(/** @param {jQuery.Event} e */ function (e) {
        e.target.setCustomValidity("");
    });
</script>

<style>
    #manual-otp {
        position-area: top;
    }

    input:valid + .validity {
        display: none
    }
</style>
<?= $template->end() ?>

