services:
    webserver:
        image: caddy:alpine
        working_dir: /var/www/webapp
        environment:
            STATIC_URL: /static
            STATIC_PATH: /var/www/webapp/assets
        volumes:
            - ./deploy/caddy:/etc/caddy:ro
            - ./var/caddy/data:/data/caddy:z
            - ./var/caddy/config:/config/caddy:z
            - ./web:/var/www/webapp
    web:
        build: web
        working_dir: /var/www/webapp
        volumes:
            - ./web:/var/www/webapp
            - ./deploy/php-fpm/php-overrides.ini:/etc/php/8.4/fpm/conf.d/90-overrides.ini
    db:
        image: mariadb
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: yes
            MARIADB_DATABASE: webstore
            MARIADB_USER: user
            MARIADB_PASSWORD: password
        volumes:
            - ./var/mysql:/var/lib/mysql:z
    phpmyadmin:
        image: phpmyadmin:alpine
        environment:
            PMA_ARBITRARY: 1
            PMA_ABSOLUTE_URI: https://