services:
    db:
        image: mariadb
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: yes
            MARIADB_DATABASE: ${DATABASE_NAME}
            MARIADB_USER: ${DATABASE_USER}
            MARIADB_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./var/mysql:/var/lib/mysql:z
        healthcheck:
            test:
              [
                  "CMD",
                  "/usr/local/bin/healthcheck.sh",
                  "--su-mysql",
                  "--connect",
                  "--innodb_initialized",
              ]
            interval: 10s
            timeout: 5s
            retries: 5
    webserver:
        build:
            context: web
            dockerfile: caddy.Dockerfile
        working_dir: /var/www/webapp
        volumes:
            - ./deploy/caddy:/etc/caddy:ro
            - ./var/caddy/data:/data/caddy:z
            - ./var/caddy/config:/config/caddy:z
            - ./web/public:/var/www/webapp/public:z
    web:
        build: web
        working_dir: /var/www/webapp
        volumes:
            - ./deploy/php-fpm/php.ini:/usr/local/etc/php/conf.d/php-overrides.ini
            - ./web/public:/var/www/webapp/public:z
            - ./web/config:/var/www/webapp/config:z
            - ./web/src:/var/www/webapp/src:z
            - ./web/views:/var/www/webapp/views:z
        env_file:
            - .env
            - path: .env.local
              required: false
        depends_on:
            db:
                condition: service_healthy
    phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: db
