services:
    db:
        ports:
            - "3306:3306"
    webserver:
        environment:
            SITE_URL: localhost
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        develop:
            watch:
                -   path: ./web/public
                    action: sync
                    target: /var/www/webapp/public
    web:
        build: web
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - ./deploy/php-fpm/php-xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        develop:
            watch:
                -   path: ./web
                    action: sync
                    target: /var/www/webapp
                    ignore:
                        - node_modules/
                -   path: ./web/composer.json
                    action: rebuild
    phpmyadmin:
        environment:
            PMA_ABSOLUTE_URI: https://localhost/phpmyadmin/
