services:
    db:
        image: mariadb
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: yes
            MARIADB_DATABASE: webstore
            MARIADB_USER: user
            MARIADB_PASSWORD: password
        volumes:
            - ./var/mysql:/var/lib/mysql:z
        healthcheck:
            test:
              [
                  "CMD",
                  "/usr/local/bin/healthcheck.sh",
                  "--su-mysql",
                  "--connect",
                  "--innodb_initialized",
              ]
            interval: 10s
            timeout: 5s
            retries: 5
    webserver:
        image: caddy:alpine
        working_dir: /var/www/webapp
        environment:
            STATIC_URL: /static
            STATIC_PATH: /var/www/webapp/assets
        volumes:
            - ./deploy/caddy:/etc/caddy:ro
            - ./web:/var/www/webapp:z
            - ./var/caddy/data:/data/caddy:z
            - ./var/caddy/config:/config/caddy:z
    web:
        build: web
        working_dir: /var/www/webapp
        volumes:
            - ./deploy/php-fpm/php-overrides.ini:/etc/php/8.4/fpm/conf.d/90-overrides.ini
            - ./web:/var/www/webapp:z
        depends_on:
            db:
                condition: service_healthy
    phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: db
            PMA_ABSOLUTE_URI: https://