services:
    db:
        ports:
            - "3306:3306"
    webserver:
        environment:
            SITE_URL: localhost
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
    web:
        build: web
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - ./deploy/php-fpm/php-dev.ini:/etc/php/8.4/cli/conf.d/91-dev-overrides.ini
        ports:
            - "9000:9000"
    phpmyadmin:
        environment:
            PMA_ABSOLUTE_URI: https://localhost/phpmyadmin/
