
### GET request to index page
GET https://localhost

###
POST https://localhost/api/user
Content-Type: application/json

{
    "username": "asdasd",
    "email": "asdasd@asdasd.com",
    "hashed_password": "wasda",
    "role": "USER",
    "is_verified": false
}

###
PUT https://localhost/api/user
Content-Type: application/json

{
    "username": "asdasd",
    "email": "asdasd@asdatt.com",
    "hashed_password": "wasda",
    "role": "USER",
    "is_verified": false
}

###
# note
POST https://localhost/address/new
Content-Type: application/x-www-form-urlencoded

?address1=asdasdasd
&address2=asdasd
&postcode=10000
